/// Explicit game / app phase machine for Chor Police Dakat Babu.
enum GamePhase {
  loading,
  home,
  modeSelection,
  createRoom,
  joinRoom,
  waitingRoom,
  gameInitialization,
  roleDistribution,
  roleReveal,
  rollByGameLead,
  rollByPolice,
  policeTurn,
  suspectSelection,
  guessConfirmation,
  result,
  scoreUpdate,
  nextRound,
  finalScore,
  gameOver,
  error,
  reconnecting,
}
